export const serieRules = [
  'Os vídeos devem ter descrição de todos os participantes (esta na Home)',
  'Toda semana terá missões para ser cumprida',
  'É necessário uma thumbnail com a logomarca da série em cada vídeo',
  'Cada vídeo poderá ser feito ao vivo ou gravado',
  'Os parceiros novos devem ter frequência no YouTube caso queiram entrar',
  'O intuito é produzir conteúdo de qualidade! (Tente ser top na hora de produzir conteúdo)',
  'Imprescindível que os Youtubers não estraguem o mapa ou usem programas como Toolbox ou outros programas parecidos',
  'De opiniões sobre a serie',
  'Não destruir o mapa',
  'Gravar episódios e não ficar jogando aleatoriamente no mapa sem fazer nada, pode jogar sem gravar desde que não fique não tenha fluxo de gravação e ficando não pode ficar fazendo coisas sem sentido no mapa (para não ficar cheio)',
  'Não pegar "roubar" itens dos outros Youtubers',
  'Dormir na hora que a galera deitar caso esteja a noite, se a pessoa não poder dormir sai do realms e volta para que os outros possam dormir',
  'O realms cabe somente 10 pessoas',
  'Cuidado com o que fala no chat',
  'Ser Family Friendly, se você faz conteúdo apelando, esquece, bora ser uma pessoa legal sem palavrões, putarias, incentivo de drogas e afins',
  'Não invadir a casa do outro (se for vender algo, coloca um baú fora de casa e a placa informando que esta vendendo e o valor)',
  'Colocar uma placa na sua casa com o seu nome para identificar',
  'Não construí na cidade e nem mesmo por debaixo dela, nem mesmo cavar por debaixo das casas dos outros integrantes',
  'Não matar o amigo, somente se ele pedir por cause de algum bug ou afins',
  'Não destruir ou modificar a construção do amigo',
  'Não escrever quem é o rei no chat do game, não sabe quem é o rei pergunta no WhatsApp interno nosso',
  'Não ofender e brigar no chat do game',
  'Não convidar ninguém de fora para entrar no mapa',
  'Não usar comando sem autorização',
  'Não alterar o tick do mapa, o padrão é 1',
  'Não expulsar ninguém, mesmo que por um acaso você tenha este perfil sem o consentimento de todos, tirando o caso de que a pessoa entrou no realm sem autorização ou que a pessoa está avacalhando muito',
  'Não invadir a mina do amigo, se for usar a mesma mina, tentar deixar organizado caso ele já deixa, se não deixa, tenta deixar organizado pra ele. Mas previra cavar contrário ao amigo',
  'Não quebrar a Farm do amigo e só usar a Farm dele se tiver uma placa de publica',
  'Não dar TP (teleporte) mesmo que esteja bugado, o mais correto é sair e entrar novamente no mapa',
  'Nunca usar comando, pelo amor'
]
