export const youtubers = [
  { name: 'Mineirim', channelLink: 'https://www.youtube.com/mineirim', logoIcon: 'https://yt3.ggpht.com/RldNtnkPRaVJCUT3MYuSP-EwaqFGxtnxgzVSOin7PzAuGf5i0jaI7Y0WyXFa_2x6YeWVqqNk=s88-c-k-c0x00ffffff-no-rj' },
  { name: 'New Player EHP', channelLink: 'https://www.youtube.com/newplayerehp', logoIcon: 'https://yt3.ggpht.com/5AI-SvVfm92JgbyG8Y3PJS9o0A7rFZ9oAK9aDmGTIg5ywuoRXPY64IG8IEbd7Izjm3qf5ubN6A=s88-c-k-c0x00ffffff-no-rj' },
  { name: 'Dyow Gamer', channelLink: 'https://www.youtube.com/DyowGamer', logoIcon: 'https://yt3.ggpht.com/ytc/AKedOLQe-z7Wtv1IC7WEZLHuk3pIFEzV5zVdXrvxb5VX=s88-c-k-c0x00ffffff-no-rj' },
  { name: 'JVVM', channelLink: 'https://www.youtube.com/JVVMYT', logoIcon: 'https://yt3.ggpht.com/mjb4ArqWQhgWUv_GpFbmwJ9__3j8RmpIT5qkkPgE3oIiSe0UJQ1kvaaAIvYMgF1Mtc1UPf-Vmw=s88-c-k-c0x00ffffff-no-rj' },
  { name: 'Mine Magic', channelLink: 'https://encurtador.com.br/blrBR', logoIcon: 'https://yt3.ggpht.com/ytc/AKedOLRsS2vC2A9MYr9QDJ20NYXLWlplzpf7Gy6jh36W=s88-c-k-c0x00ffffff-no-rj' },
  { name: 'TIOZÉ', channelLink: 'https://encurtador.com.br/rtAGL', logoIcon: 'https://yt3.ggpht.com/PI_ZeswglsvidD3dfC9Bs_6TP2xy2oIwlhraewcqHoSPeBofdKZKvhc7-hjAHkBicPiw311LjQ0=s88-c-k-c0x00ffffff-no-rj' },
  { name: 'Tonhao Santos', channelLink: 'https://www.youtube.com/TonhaoSantos', logoIcon: 'https://yt3.ggpht.com/ytc/AKedOLRXin364ZXEfpKvB7Zo7InSzWJhMgFzXxPhBduWpw=s88-c-k-c0x00ffffff-no-rj' },
  { name: 'Coder Felipe', channelLink: 'https://www.youtube.com/coderfelipe', logoIcon: 'https://yt3.ggpht.com/TMOloQ4swl4ahDUCImJeqJecdUd9JstzIlLwphrNe6fcQW8CUnkD2FINxmetdXjJaFyIYDbU8A=s88-c-k-c0x00ffffff-no-rj' },
  { name: 'G Paulo', channelLink: 'https://www.youtube.com/GPaulo1k', logoIcon: 'https://yt3.ggpht.com/_62g-oez4C_BTBvzKjYhlvnuacoxDBFzeUtN4NUWhN1B9KbOXWaWB1mDlgXxDxmfIQqj92AI70o=s88-c-k-c0x00ffffff-no-rj' },
  { name: 'D.A.O play', channelLink: 'https://www.youtube.com/DAOplaybora1k', logoIcon: 'https://yt3.ggpht.com/A5MeF0w8DMH8xAHdc05MTP1y2eQXgoXtQAaDIFgMXAM4t_orCvu4dkrfA3fnmzX2l7hmNhYhQSw=s88-c-k-c0x00ffffff-no-rj' },
  { name: 'Paloma Santos', channelLink: 'https://www.youtube.com/PalomaSantos', logoIcon: 'https://yt3.ggpht.com/6ZYocLM5HxWezWCO0DCVrVlETQ8P4du-4xFN0M9uJfIMeayYzoirVoL1TGStvcJr7UruuPkqMg=s88-c-k-c0x00ffffff-no-rj' },
  { name: 'Revolt Z', channelLink: 'https://www.youtube.com/c/RevoltZi', logoIcon: 'https://yt3.ggpht.com/DVJm1ALO0k1g60Bq1rbuqXsycpJr2X9orMJ0vgVr_rqKfAuGLPOBgGvhNa44sTpti5eedTlz_A=s88-c-k-c0x00ffffff-no-rj' },
  { name: 'Newton Gamer Oficial', channelLink: 'https://encurtee.me/jnlwr', logoIcon: 'https://yt3.ggpht.com/tL_XOULRlq62fQP5g6cweUMO2YyUB6mI7EAK9JWXhjjAe4sjyQo22MgjzBOy_u1vu1fV3Gleqg=s88-c-k-c0x00ffffff-no-rj' },
  { name: 'Rafa Game', channelLink: 'https://www.youtube.com/c/Rafagame', logoIcon: 'https://yt3.ggpht.com/ytc/AKedOLSCytwOLdfaU4Nc7Nz5xdbLPrj1yjKwqMN8wk-R=s88-c-k-c0x00ffffff-no-rj' },
  { name: 'RXBGAMES', channelLink: 'https://www.youtube.com/c/RXBGAMES', logoIcon: 'https://yt3.ggpht.com/ytc/AKedOLSaNveFakN2z6E1_E5HcU829w2_bLQ2UO_qlBKaog=s88-c-k-c0x00ffffff-no-rj' },
  { name: 'Joninhas', channelLink: 'https://encurtee.me/hk5va', logoIcon: 'https://yt3.ggpht.com/uZCWbYdmTa8uPVyPWjTER0snc8aiIkDbIN2oM4I7vGYtnRrEsq1SNlMG179lUi8J3GNN1WigyA=s88-c-k-c0x00ffffff-no-rj' },
  { name: 'Família Plays', channelLink: 'https://encurtee.me/l-tfa', logoIcon: 'https://yt3.ggpht.com/ytc/AKedOLSteALrMkMf2HNc5kqTeNjkRcvCmzbvQRjrkeEq=s88-c-k-c0x00ffffff-no-rj' }
]
